version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5433  # Change the database port number
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=backend_assignment
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=5c4929e0c46c77009c62e47b534fb20a640fc89e057452b89b34b6b59c1590bc
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=backend_assignment
    ports:
      - "5433:5432"  # Map container port 5432 to host port 5433
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
  postgres-db:
